"""Patient model/schema for OA Assist.

A *user* is whoever signed in (the doctor or account holder). A *patient* is
somebody whose X-ray, symptoms and gait get assessed. They are deliberately
separate: a signed-in user is never automatically a patient, and one user can
manage many patients.

Relationship:

    User (JWT)  ->  Patient  ->  Assessment (xray / symptoms / gait)

The patient document is intentionally minimal. It holds identity and the few
demographic fields needed to label a scan. It does **not** hold medical data:
that lives in the assessment documents, which reference `patient_id`.

Design notes:
- ``patient_id`` (for example ``OA-0001``) is the public, human-readable
  identifier used in the URL space. It is generated by the backend from a global
  counter, never derived from the name, and never accepted from the client.
- ``user_id`` is the MongoDB ``ObjectId`` of the owning user. It is taken from
  the verified JWT, so a client cannot choose who owns a patient.
- Ownership is enforced on every query by filtering on ``user_id`` together with
  ``patient_id``, so one user can never read or delete another user's patient.
"""

from __future__ import annotations

import re
from datetime import datetime
from typing import Any, Mapping, Optional

from pydantic import BaseModel, Field, field_validator
from pymongo import ASCENDING, DESCENDING, ReturnDocument

from ..database import get_database

# Name of the MongoDB collection that stores patients.
PATIENTS_COLLECTION = "patients"

# Name of the MongoDB collection that stores the id counters.
COUNTERS_COLLECTION = "counters"

# Document id of the patient-id counter inside `counters`.
PATIENT_ID_COUNTER = "patient_id"

# Every generated id starts with this prefix: OA-0001, OA-0002, ...
PATIENT_ID_PREFIX = "OA"

# Ids are zero padded to this width. Ids above OA-9999 simply grow wider
# (OA-10000) instead of wrapping, so no id is ever reused.
PATIENT_ID_WIDTH = 4

# Shape of a valid patient id, used to reject malformed ids before any query.
PATIENT_ID_PATTERN = re.compile(r"^OA-\d{4,}$")

# Accepted values for the optional `gender` field.
GENDERS = ("Male", "Female", "Other", "Prefer not to say")


def get_patients_collection():
    """Return the async `patients` collection from the OA Assist database."""
    return get_database()[PATIENTS_COLLECTION]


def get_counters_collection():
    """Return the async `counters` collection from the OA Assist database."""
    return get_database()[COUNTERS_COLLECTION]


def format_patient_id(sequence: int) -> str:
    """Turn a counter value into a public patient id, for example `OA-0007`."""
    return f"{PATIENT_ID_PREFIX}-{sequence:0{PATIENT_ID_WIDTH}d}"


def is_valid_patient_id(value: str) -> bool:
    """Return True when `value` looks like a patient id this app could issue."""
    return bool(PATIENT_ID_PATTERN.fullmatch(value or ""))


async def reserve_patient_id() -> str:
    """Reserve and return the next global patient id.

    `find_one_and_update` with `upsert` increments the counter and returns the
    new value in a single atomic MongoDB operation, so two users creating a
    patient at the same moment can never be handed the same id. Gaps are
    possible if a request fails after the counter was incremented, which is
    harmless: ids stay unique and monotonic.
    """
    counter = await get_counters_collection().find_one_and_update(
        {"_id": PATIENT_ID_COUNTER},
        {"$inc": {"seq": 1}},
        upsert=True,
        return_document=ReturnDocument.AFTER,
    )

    return format_patient_id(counter["seq"])


class PatientCreate(BaseModel):
    """Data accepted when creating a patient.

    `user_id` is intentionally absent. Ownership is taken from the verified JWT
    in the route and never from the request body, so sending a `user_id` here
    has no effect.
    """

    name: str = Field(
        ...,
        min_length=1,
        max_length=120,
        description="Patient's name. Used for display only, never as the identifier.",
        examples=["Rahul Khan"],
    )
    age: Optional[int] = Field(
        default=None,
        ge=0,
        le=130,
        description="Age in years. Optional.",
        examples=[45],
    )
    gender: Optional[str] = Field(
        default=None,
        description="Optional gender. One of Male, Female, Other or Prefer not to say.",
        examples=["Male"],
    )

    @field_validator("name")
    @classmethod
    def clean_name(cls, value: str) -> str:
        """Collapse runs of whitespace and reject a name of only whitespace."""
        cleaned = " ".join(value.split())

        if not cleaned:
            raise ValueError("Patient name is required.")

        return cleaned

    @field_validator("gender")
    @classmethod
    def check_gender(cls, value: Optional[str]) -> Optional[str]:
        """Normalize casing and reject a gender outside the allowed list."""
        if value is None:
            return None

        cleaned = value.strip()

        if not cleaned:
            # An empty string means "not supplied", not an invalid value.
            return None

        for allowed in GENDERS:
            if cleaned.casefold() == allowed.casefold():
                return allowed

        raise ValueError(f"Gender must be one of: {', '.join(GENDERS)}.")


class PatientPublic(BaseModel):
    """Safe shape of a patient for API responses.

    Never exposes the MongoDB `_id` and never includes any medical data.
    """

    patient_id: str = Field(..., examples=["OA-0001"])
    name: str = Field(..., examples=["Rahul Khan"])
    age: Optional[int] = Field(default=None, examples=[45])
    gender: Optional[str] = Field(default=None, examples=["Male"])
    created_at: datetime


def patient_to_public(document: Mapping[str, Any]) -> PatientPublic:
    """Build the response shape from a stored patient document."""
    return PatientPublic(
        patient_id=document["patient_id"],
        name=document["name"],
        age=document.get("age"),
        gender=document.get("gender"),
        created_at=document["created_at"],
    )


async def ensure_patient_indexes() -> None:
    """Create the indexes the patients collection relies on.

    Safe to call more than once: MongoDB only builds an index that is missing.

    - ``uniq_patient_id`` is the hard guarantee that a patient id is never
      issued twice, even if the counter were ever rolled back by hand.
    - ``user_created_at`` matches the ownership-filtered listing query, which
      sorts a single user's patients newest first.
    """
    collection = get_patients_collection()

    await collection.create_index(
        "patient_id", unique=True, name="uniq_patient_id"
    )
    await collection.create_index(
        [("user_id", ASCENDING), ("created_at", DESCENDING)],
        name="user_created_at",
    )
