"""Patient routes for OA Assist.

Every route here is protected: the caller must present a valid access token, and
the `user_id` that scopes the patient is taken from that token and never from
the request body or query string.

Ownership rule applied throughout: a query always matches `patient_id` **and**
`user_id` together. A patient that exists but belongs to somebody else is
reported as `404`, not `403`, so this API never reveals that another user's
patient id is real.
"""

from __future__ import annotations

from typing import Any, List, Optional

from bson import ObjectId
from bson.errors import InvalidId
from fastapi import APIRouter, Depends, HTTPException, status
from pydantic import BaseModel, Field
from pymongo import DESCENDING
from pymongo.errors import DuplicateKeyError, PyMongoError

from ..dependencies import get_current_user
from ..models.assessment import count_patient_assessments
from ..models.patient import (
    PatientCreate,
    PatientPublic,
    get_patients_collection,
    is_valid_patient_id,
    patient_to_public,
    reserve_patient_id,
)
from ..models.user import UserSession, utc_now

router = APIRouter()

# Returned for a patient_id that is not in the OA-0001 format. This is a client
# mistake rather than a missing resource, so it gets its own 400 response.
INVALID_PATIENT_ID = "Invalid patient ID. Expected the format OA-0001."

# Returned for a well-formed id that either does not exist or belongs to another
# user. Both cases are reported identically on purpose.
PATIENT_NOT_FOUND = "Patient not found."

# The database rejected the write, not the request.
DATABASE_UNAVAILABLE = "The database is currently unavailable."


class DeletePatientResponse(BaseModel):
    """Confirmation returned after a patient is removed."""

    message: str = Field(..., examples=["Patient deleted successfully"])
    patient_id: str = Field(..., examples=["OA-0001"])


def _owner_id(current_user: UserSession) -> ObjectId:
    """Return the caller's id as an ObjectId, for use in an ownership query.

    `get_current_user` already produced this id from the verified token, so it is
    always a valid ObjectId; the guard only protects against future changes.

    Raises:
        HTTPException: 401 if the id is somehow not usable.
    """
    try:
        return ObjectId(current_user.id)
    except (InvalidId, TypeError):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Could not validate credentials.",
            headers={"WWW-Authenticate": "Bearer"},
        ) from None


def _validate_patient_id(patient_id: str) -> str:
    """Reject a malformed id before it reaches MongoDB.

    Raises:
        HTTPException: 400 when the id is not in the `OA-0001` format.
    """
    if not is_valid_patient_id(patient_id):
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=INVALID_PATIENT_ID,
        )

    return patient_id


async def _find_owned_patient(patient_id: str, owner_id: ObjectId) -> Optional[dict[str, Any]]:
    """Return the caller's patient document, or None if it is not theirs."""
    return await get_patients_collection().find_one(
        {"patient_id": patient_id, "user_id": owner_id}
    )


@router.post(
    "",
    response_model=PatientPublic,
    status_code=status.HTTP_201_CREATED,
    summary="Create a patient for the authenticated user",
)
async def create_patient(
    payload: PatientCreate,
    current_user: UserSession = Depends(get_current_user),
) -> PatientPublic:
    """Create a patient owned by the signed-in user.

    - `patient_id` is generated by the backend from a global counter, so it is
      unique across all users and is never taken from the request.
    - `user_id` comes from the verified JWT. A `user_id` sent in the body is
      ignored.
    - The document stores identity only. Assessment results are not saved here.
    """
    patients = get_patients_collection()
    owner_id = _owner_id(current_user)

    # The unique index on patient_id is the real guarantee against a duplicate.
    # The counter makes a collision practically impossible; the retry covers the
    # pathological case where it somehow happens anyway.
    for _ in range(3):
        patient_id = await reserve_patient_id()

        document = {
            "patient_id": patient_id,
            "user_id": owner_id,
            "name": payload.name,
            "age": payload.age,
            "gender": payload.gender,
            "created_at": utc_now(),
        }

        try:
            await patients.insert_one(document)
        except DuplicateKeyError:
            continue
        except PyMongoError:
            raise HTTPException(
                status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
                detail=DATABASE_UNAVAILABLE,
            ) from None

        return patient_to_public(document)

    raise HTTPException(
        status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
        detail="The patient could not be created. Please try again.",
    )


@router.get(
    "",
    response_model=List[PatientPublic],
    status_code=status.HTTP_200_OK,
    summary="List the authenticated user's patients, newest first",
)
async def list_patients(
    current_user: UserSession = Depends(get_current_user),
) -> List[PatientPublic]:
    """Return every patient owned by the signed-in user.

    Scoped by the id in the verified token, so a user can never list somebody
    else's patients. Sorted newest first. An account with no patients gets an
    empty list, not an error.
    """
    try:
        cursor = (
            get_patients_collection()
            .find({"user_id": _owner_id(current_user)})
            .sort([("created_at", DESCENDING), ("_id", DESCENDING)])
        )
        documents = await cursor.to_list(length=None)
    except PyMongoError:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail=DATABASE_UNAVAILABLE,
        ) from None

    return [patient_to_public(document) for document in documents]


@router.get(
    "/{patient_id}",
    response_model=PatientPublic,
    status_code=status.HTTP_200_OK,
    summary="Return one of the authenticated user's patients",
)
async def read_patient(
    patient_id: str,
    current_user: UserSession = Depends(get_current_user),
) -> PatientPublic:
    """Return a single patient.

    Requires `Authorization: Bearer <access_token>`.

    - `400` when `patient_id` is not in the `OA-0001` format.
    - `404` when the id does not exist, or when it belongs to another user. The
      two cases are deliberately indistinguishable.
    """
    _validate_patient_id(patient_id)

    try:
        document = await _find_owned_patient(patient_id, _owner_id(current_user))
    except PyMongoError:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail=DATABASE_UNAVAILABLE,
        ) from None

    if document is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=PATIENT_NOT_FOUND,
        )

    return patient_to_public(document)


@router.delete(
    "/{patient_id}",
    response_model=DeletePatientResponse,
    status_code=status.HTTP_200_OK,
    summary="Delete one of the authenticated user's patients",
)
async def delete_patient(
    patient_id: str,
    current_user: UserSession = Depends(get_current_user),
) -> DeletePatientResponse:
    """Delete a patient owned by the signed-in user.

    Requires `Authorization: Bearer <access_token>`.

    - `400` when `patient_id` is not in the `OA-0001` format.
    - `404` when the id does not exist, or belongs to another user.
    - `409` when assessments already reference this patient.

    The `409` guard is deliberate. Assessments are not implemented yet, but the
    check is live now, so the day saving is switched on a patient can no longer
    be deleted out from under its history. There is no cascade delete: a patient
    with assessments must be dealt with explicitly.
    """
    _validate_patient_id(patient_id)
    owner_id = _owner_id(current_user)

    try:
        document = await _find_owned_patient(patient_id, owner_id)

        if document is None:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=PATIENT_NOT_FOUND,
            )

        # Refuse while the patient still has assessment history.
        assessment_count = await count_patient_assessments(patient_id)

        if assessment_count:
            raise HTTPException(
                status_code=status.HTTP_409_CONFLICT,
                detail=(
                    "This patient has assessment results and cannot be deleted. "
                    "Remove or reassign those assessments first."
                ),
            )

        # Re-check ownership inside the delete itself, so a concurrent request
        # cannot widen the blast radius of this route.
        result = await get_patients_collection().delete_one(
            {"patient_id": patient_id, "user_id": owner_id}
        )
    except HTTPException:
        raise
    except PyMongoError:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail=DATABASE_UNAVAILABLE,
        ) from None

    if result.deleted_count == 0:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=PATIENT_NOT_FOUND,
        )

    return DeletePatientResponse(
        message="Patient deleted successfully",
        patient_id=patient_id,
    )
